[package]
name = "fidan-codegen-llvm"
version.workspace = true
edition.workspace = true
license-file.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = []
llvm-toolchain-21 = [
  "dep:fidan-ast",
  "dep:fidan-stdlib",
  "dep:inkwell",
  "dep:llvm-sys",
  "inkwell/llvm21-1",
]

[dependencies]
anyhow = { workspace = true }
fidan-lexer = { workspace = true }
fidan-mir = { workspace = true }
fidan-ast = { workspace = true, optional = true }
fidan-stdlib = { workspace = true, optional = true }
inkwell = { workspace = true, optional = true }
llvm-sys = { version = "211", optional = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
fidan-ast = { workspace = true }
fidan-source = { workspace = true }
