# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Fidan.Fidan
PackageVersion: 0.0.0
InstallerType: inno
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/fidan-lang/fidan/releases/{version}/download/fidan_windows_bootstrap_v{version}.exe
    InstallerSha256: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
ManifestType: installer
ManifestVersion: 1.10.0
